#! /bin/bash
#
# Generated by the utility: /z/util/collect_git_checked_out_branch_recusively.sh 
#
# Checkout each git repository to the given branch/commit or list them
#

mode=h;
while getopts ":hlc" opt ; do
  #echo opt+arg = "$opt$OPTARG"
  case "$opt$OPTARG" in
  l )
    mode=h;
    ;;

  c )
    mode=c;
    ;;

  r )
    mode=r;
    ;;

  * )
    cat <<EOH
checkout_to_known_git_branches_recursive.sh options

Options:

-h      : print this help 
-l      : LIST the branch/commit for each git repository (directory) registered in this script.
-c      : CHECKOUT each git repository to the BRANCH registered in this script.
-r      : CHECKOUT/REVERT each git repository to the COMMIT registered in this script.

Note:

Use the '-r' option to set each repository to an exact commit position, which is useful if,
for instance, you wish to reproduce this registered previous software state (which may 
represent a software release) which you wish to analyze/debug.

EOH
    exit 1;
    ;;
  esac
done

if test "$mode" = "h" ; then
  cat <<EOH

Git repository directory                    :: commit hash                         / branch name
--------------------------------------------::--------------------------------------------------
EOH
fi



# args: DIR COMMIT [BRANCH]
git_repo_checkout_branch() {
  if test "$mode" = "c" || test "$mode" = "r" ; then
    if test -d "$1" ; then
      pushd "$1"                                                               2> /dev/null  > /dev/null
      if test "$mode" = "c" ; then
        if test -n "$3" ; then
          # make sure the branch is created locally and is a tracking branch:
          git branch --track "$3" "remotes/origin/$3"                            2> /dev/null  > /dev/null
          git checkout "$3"
        else
          git checkout master
        fi
      else
        git checkout "$2"
      fi
      popd                                                                     2> /dev/null  > /dev/null
    fi
  else
    if test -d "$1" ; then
      printf "%-43s :: %s / %s\n" "$1" "$2" "$3"
    else
      printf "%-43s :: %s / %s\n" "[DIRECTORY DOES NOT EXIST!] $1" "$2" "$3"
    fi
  fi
}


#
# Make sure we switch to the utility directory as all the relative paths for the repositories
# are based off that path!
#
pushd $(dirname $0)                                                            2> /dev/null  > /dev/null



#
# The registered repositories:
#

git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF" b083226bb9a61ea168cbc61c717e7f23c7790534 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/book/mupdf_explored" d0b61493aa78124be10b21f90f027a123ca986c9 main
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/curl" 9edeb307a9a845e074cd5e33b11c52c0331fddef master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/extract" 82479d3eef76e3d12d4a785f2a14233c029d9fce master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/freeglut" eb0ebea37713df5b9514532f2645fb2d815282e3 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/freetype" 0fae66cd81177c0ce531c893331abea6edd634fa master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/gumbo-parser" 0213cf039dec99552b42122c57245cb8432f00eb mupdf
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/harfbuzz" c811ecfdcc55f0fb08343296432f5f9fde353f1a master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/jbig2dec" 4bcea38183431540eb3eb8d5b2b426fd33ca7fd4 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/jpeginfo" 603b7742f757417551856e9660414ec7728fb1b7 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/langdata_LSTM" f0714d60cdc221fceb11787acb5e35b3937643ae master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/lcms2" e9b540ab86bc7a0b70066f73110a01e327b896ab master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/leptonica" fafe304ce084c19802c18c31d69454900604e804 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/libjpeg" 2727a4365ae480ecda656e8372f4c782c8dcc2df master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/libpng" 0d7f2823142248774373f6e6fcfd2dbf4927acb1 libpng16
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/libtiff" f81969dcd03648d3306d598ec0fa28257ae58cf1 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/mujs" ea943f10bbf08c13f5d1d4f3260109865edfb01d master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/openjpeg" 788bb6869cefe1e94d30e7e7a846ca35c60d24fe master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee" 905701b218cb17e5ed1ae86e5415c7f860bdc62b main
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/BLAKE3" 0359065018e2bafa31d319010ec5cebc35ad4393 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/CPython" 3243e8a4b4b4cf321f9b28335d565742a34b1976 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/EasyLogger" fd21dfe75316f909f23ae35d1bf582b85dec15eb master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/FastBinaryEncoding" f0948021f009eed367fd7dfe9a2faa1a1ef373c1 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/HDF5" ae9b4026a956f2ece490a10497b3ff7e4435de9e develop
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/HighFive-HDF5" e582076fb5b4dd654738c24c2d40517d11512ca6 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/HighFive-HDF5/deps/hpc-coding-conventions" 609237f2774309ed08c92c92248e2f39de5b11d2 
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/ImageMagick" 923b9c1801de6365daa10d14d09ca8e2a1c5064f main
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/MITIE-nlp" b6f454fbc8cbca9269357f10114c90f7f6bc9afd master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/OpenImageIO" 8faa8929034e872b80a99f09e182805686ee73b4 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/atlas" fe29eec83868f2b328f08c133ec92c3ffd94a326 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/bebop" c8ec6176b00ffaca228af9892dcd1a721356ef22 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/c-blosc" 7435f28dd08606bd51ab42b49b0e654547becac4 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/civet-webserver" 68cd593cef47e161105e80d5a8234ef1fd275016 bel2125_civet
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/clipp" 2c32b2f1f7cc530b1ec1f62c92f698643bb368db master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/dlib" 3162f93c5d303e593337ab8e40d79b385e025d3c master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/flatbuffers" bf90612007f2163857eaefd5ab1989a9fd7fc253 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/flatcc" 0d47180eabc55ecd7a9f865477f27add74111da7 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/h5cpp-HDF5" 08aedc1b9592430bc915f30d4ffd3531be7b1a01 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/hocr-fileformat" baefb2da319cbad3380e1d3459f2f157b41a0bd8 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/hocr-spec" 2b8a90267574855df8f5766d8391aefc5824f924 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/hocr-tools" b3e380779e5c88ad99dca2a6b8b292c0f375fd68 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/hunspell" 8a2fdfe5a6bb1cbafc04b0c8486abcefd17ad903 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/hunspell-hyphen" 73dd2967c8e1e4f6d7334ee9e539a323d6e66cbd master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/hyperscan" 64a995bf445d86b74eb0f375624ffc85682eadfe master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/inih" 0b9092e80acc8dc820103c6a0cb9c030e3ca1a32 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/iniparser" f858275f7f307eecba84c2f5429483f9f28007f8 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/jerryscript" a95a0b3539cba0c0b8015bdc6569529ea9562d5f master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/log4cplus" 3a6df071e056fef6e5d0544e6e68e10d5f677101 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/lua" ef9f07c408cedff07da40fb430b12b6cc120cae1 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/luaJIT" ec6edc5c39c25e4eb3fca51b753f9995e97215da v2.1
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/math-atlas" fe29eec83868f2b328f08c133ec92c3ffd94a326 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/mlpack" 974344117bbf856d09689ce156daaee4e836ef37 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/olena" 58d4f5dfe6dbf87289d20b9ce675d50bae1cb74d master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/opencv" fd5848a4dac3161719b527f3d5ec5e3392e5e773 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/popt" 45795290fce544204939166cea6677ed9165c29a master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/rapidJSON" 13dfc96c9c2b104be7b0b09a9f6e06871ed3e81d master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/rapidJSON/thirdparty/gtest" ba96d0b1161f540656efdaed035b3c062b60e006 
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/tre" 2ad33edb5f9e9991c6b4a78105eacb2c1b9d4048 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/unicode-cldr" 87058620eae1e6d1acb44fa706fc19a5cfab72bf master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/unicode-icu" 00cedadc92427612ec76eca4e7388d43295a2d8e master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/xtensor" ed3cab15994549346aa420d29ff8bae131c3d947 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/xtensor-blas" ab0e77483c71e6c35604fc15fe6c385ee8b29b47 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/xtensor-io" 344bef3c670193f6da9c42d517328c1e3e608694 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/yyjson" ae5f700249c8bb4456cd199f867e86a126a4424f master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/owemdjee/zlog" 94f4aa6f7939b1b8cec7d7f0908f9b850d245611 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessconfigs" 3decf1c8252ba6dbeef0bf908f4b0aab7f18d113 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessdata" 4767ea922bcc460e70b87b1d303ebdfed0897da8 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessdata/tessconfigs" 3decf1c8252ba6dbeef0bf908f4b0aab7f18d113 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessdata_best" e2aad9b983032bb1beff9133104a67cdbb87ca4d master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessdata_best/tessconfigs" 3decf1c8252ba6dbeef0bf908f4b0aab7f18d113 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessdata_contrib" 5860cde5da2aa530a0d6cb1b9de5f526a7172d81 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessdata_fast" 65727574dfcd264acbb0c3e07860e4e9e9b22185 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessdata_fast/tessconfigs" 3decf1c8252ba6dbeef0bf908f4b0aab7f18d113 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tessdoc" 70c4bac5ff33860f93c13b4123b52f4411058fee master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tesseract" 57c9fe1b32dda347fcf98354b1a2c77983ff5a24 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tesseract/abseil" e7ca23acac146b10edc4f752edd0bd28b0f14ea3 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tesseract/googletest" 554ce00adb61d100b306ec7a6538a4eab370fc0e master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tesseract/test" e27d9566917d7d167636a7d0cd59bcfb2c61c7eb master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tesseract_docs" 4d62defbe606a2ae78113e14c374e4e418b2040e master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tesseract_langdata" 707b19d69e6563fb19ae0137cbcf4b4ec7177252 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/tesstrain" 404849b783456cd86a33a5fc32cd0dfcc46b654c master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/MuPDF/thirdparty/zlib" 2f86ec39166d7d902e6af0dbe55a2ad5416c100f master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/Qiqqa.Build/Packaging/InnoDependencyInstaller" 03273f2be98f8079ddb7809315b01890be903178 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/Qiqqa.Build/Packaging/dotnet-deployment-tools" d914c01d5dd9c7f716f555049a11e11566e27a8e master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts" 1289101d4cd9ff9bb02a06980d830c7065240cc8 main
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Commissioner" 908505ecc459c8fbf74b4c9d6d99b76321e6fb71 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Fah-Kwang" 7b16186dadf959e79ded967a7620bfb05600fcaf master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Fira" fd8c8c0a3d353cd99e8ca1662942d165e6961407 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/FiraCode" ef7c9b1593ea809f6a1e8f1c978331261d7db6ac master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Georama" 35ab2bf44e32a570943fdd86890e49ca4cf0b522 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Grenze" 1a25fb0c60fc262954a7e2fd08dd8a5e0a05b8d3 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Jost" 35f141c970538f1ed0f235789c19156b3ce2a762 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Newsreader" cfcb4f7af0e52c25e8df2a2431814c8e5fe2e155 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Saira" cc4502bd3ea6bdcd2aedb7f5a12ba7945685ab87 master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/docs-src/_meta/fonts/Spectral" 68414e1f632007dd6f51d1fa45bc365881aa2e2b master
git_repo_checkout_branch "../../../../../w/Projects/sites/library.visyond.gov/80/lib/tooling/qiqqa/thirdparty/WpfScreenHelper" 2593cfe3f03a84b61433dbd800d4c5b22362fe67 master

# --- all done ---

popd                                                                           2> /dev/null  > /dev/null

