//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Template_App1.Properties {
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF_Template_App1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to wts.ItemName.
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellPageRibbonHomeGroupCommon1Header.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCommon1Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCommon1Header", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellPageRibbonHomeGroupCommon2Header.
        /// </summary>
        public static string ShellPageRibbonHomeGroupCommon2Header {
            get {
                return ResourceManager.GetString("ShellPageRibbonHomeGroupCommon2Header", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellPageRibbonTabHomeHeader.
        /// </summary>
        public static string ShellPageRibbonTabHomeHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonTabHomeHeader", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageBackButtonTooltip
        /// </summary>
        public static string WebViewPageBackButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageBackButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageForwardButtonTooltip
        /// </summary>
        public static string WebViewPageForwardButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageForwardButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageLoadingText
        /// </summary>
        public static string WebViewPageLoadingText {
            get {
                return ResourceManager.GetString("WebViewPageLoadingText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageFaildedMessage
        /// </summary>
        public static string WebViewPageFaildedMessage {
            get {
                return ResourceManager.GetString("WebViewPageFaildedMessage", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageRefreshButtonTooltip
        /// </summary>
        public static string WebViewPageRefreshButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageRefreshButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to WebViewPageOpenInBrowserButtonTooltip
        /// </summary>
        public static string WebViewPageOpenInBrowserButtonTooltip {
            get {
                return ResourceManager.GetString("WebViewPageOpenInBrowserButtonTooltip", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to Sample Orders.
        /// </summary>
        public static string MasterDetailListDescription {
            get {
                return ResourceManager.GetString("MasterDetailListDescription", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to MasterDetail.
        /// </summary>
        public static string MasterDetailPageTitle {
            get {
                return ResourceManager.GetString("MasterDetailPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ContentGrid.
        /// </summary>
        public static string ContentGridPageTitle {
            get {
                return ResourceManager.GetString("ContentGridPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DataGrid.
        /// </summary>
        public static string DataGridPageTitle {
            get {
                return ResourceManager.GetString("DataGridPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
            ///   Looks up a localized string similar to Settings page placeholder text.  Your app description goes here..
            /// </summary>
            public static string SettingsPageAboutText {
                get {
                    return ResourceManager.GetString("SettingsPageAboutText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to About this application.
            /// </summary>
            public static string SettingsPageAboutTitle {
                get {
                    return ResourceManager.GetString("SettingsPageAboutTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Choose Theme.
            /// </summary>
            public static string SettingsPageChooseThemeText {
                get {
                    return ResourceManager.GetString("SettingsPageChooseThemeText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Personalization.
            /// </summary>
            public static string SettingsPagePersonalizationTitle {
                get {
                    return ResourceManager.GetString("SettingsPagePersonalizationTitle", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Privacy Statement.
            /// </summary>
            public static string SettingsPagePrivacyStatementText {
                get {
                    return ResourceManager.GetString("SettingsPagePrivacyStatementText", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Dark.
            /// </summary>
            public static string SettingsPageRadioButtonDarkTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonDarkTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Light.
            /// </summary>
            public static string SettingsPageRadioButtonLightTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonLightTheme", resourceCulture);
                }
            }
    
            /// <summary>
            ///   Looks up a localized string similar to Default.
            /// </summary>
            public static string SettingsPageRadioButtonWindowsDefaultTheme {
                get {
                    return ResourceManager.GetString("SettingsPageRadioButtonWindowsDefaultTheme", resourceCulture);
                }
            }
    
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to ShellPageRibbonBackstageTabSettingsHeader.
        /// </summary>
        public static string ShellPageRibbonBackstageTabSettingsHeader {
            get {
                return ResourceManager.GetString("ShellPageRibbonBackstageTabSettingsHeader", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DialogAuthenticationTitle.
        /// </summary>
        public static string DialogAuthenticationTitle {
            get {
                return ResourceManager.GetString("DialogAuthenticationTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DialogNoNetworkAvailableContent.
        /// </summary>
        public static string DialogNoNetworkAvailableContent {
            get {
                return ResourceManager.GetString("DialogNoNetworkAvailableContent", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to DialogStatusUnknownErrorContent.
        /// </summary>
        public static string DialogStatusUnknownErrorContent {
            get {
                return ResourceManager.GetString("DialogStatusUnknownErrorContent", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageLogInButtonText.
        /// </summary>
        public static string SettingsPageLogInButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogInButtonText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageNoUserLoggedInText.
        /// </summary>
        public static string SettingsPageNoUserLoggedInText {
            get {
                return ResourceManager.GetString("SettingsPageNoUserLoggedInText", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageUserTitle.
        /// </summary>
        public static string SettingsPageUserTitle {
            get {
                return ResourceManager.GetString("SettingsPageUserTitle", resourceCulture);
            }
        }
    
        /// <summary>
        ///   Looks up a localized string similar to SettingsPageLogOutButtonText.
        /// </summary>
        public static string SettingsPageLogOutButtonText {
            get {
                return ResourceManager.GetString("SettingsPageLogOutButtonText", resourceCulture);
            }
        }
    }
}
